services:

  db:
    image: postgres:15
    container_name: taskmanager-db
    environment:
      POSTGRES_USER: merul
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: TaskManagerDB
      PGDATABASE: TaskManagerDB
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U merul"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: taskmanager-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TaskManagerDB
      SPRING_DATASOURCE_USERNAME: merul
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      db:
        condition: service_healthy
volumes:
  dbdata:
